/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exibir.Imagens.Em.Swing;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author flavio-silva
 */
public class CarregaImagemV2 extends javax.swing.JFrame {

    public CarregaImagemV2() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Sair = new javax.swing.JButton();
        jButton_Guardioes = new javax.swing.JButton();
        jButton_Hobbit = new javax.swing.JButton();
        jButton_DebyELoide = new javax.swing.JButton();
        jButton_Paddington = new javax.swing.JButton();
        jButton_HorribleBoss = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Teste Exibir Imagem");

        jButton_Sair.setText("Sair");
        jButton_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SairActionPerformed(evt);
            }
        });

        jButton_Guardioes.setText("Guardiões");
        jButton_Guardioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardioesActionPerformed(evt);
            }
        });

        jButton_Hobbit.setText("Hobbit");
        jButton_Hobbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HobbitActionPerformed(evt);
            }
        });

        jButton_DebyELoide.setText("Deby&Loide");
        jButton_DebyELoide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DebyELoideActionPerformed(evt);
            }
        });

        jButton_Paddington.setText("Paddington");
        jButton_Paddington.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PaddingtonActionPerformed(evt);
            }
        });

        jButton_HorribleBoss.setText("HorribleBoss");
        jButton_HorribleBoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HorribleBossActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_HorribleBoss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_Paddington, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Guardioes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_DebyELoide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Hobbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton_Sair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Sair)
                    .addComponent(jButton_Guardioes))
                .addGap(12, 12, 12)
                .addComponent(jButton_Hobbit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_DebyELoide)
                .addGap(18, 18, 18)
                .addComponent(jButton_Paddington)
                .addGap(18, 18, 18)
                .addComponent(jButton_HorribleBoss)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_SairActionPerformed

    private void jButton_GuardioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardioesActionPerformed

        //String imagem = "/home/flavio-silva/1.BackupDadosIn2012-02-12/1.jpg";
        String imagem = "./1.jpg";
        
        ExibirImagem ei = new ExibirImagem(this,true,imagem);
        ei.setVisible(true);

    }//GEN-LAST:event_jButton_GuardioesActionPerformed

    private void jButton_HobbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HobbitActionPerformed
        
        String imagem = "./2.jpg";
        
        ExibirImagem ei = new ExibirImagem(this,true,imagem);
        ei.setVisible(true);
    }//GEN-LAST:event_jButton_HobbitActionPerformed

    private void jButton_DebyELoideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DebyELoideActionPerformed
        String imagem = "./3.jpg";
        
        ExibirImagem ei = new ExibirImagem(this,true,imagem);
        ei.setVisible(true);
    }//GEN-LAST:event_jButton_DebyELoideActionPerformed

    private void jButton_PaddingtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PaddingtonActionPerformed
        String imagem = "./4.jpg";
        
        ExibirImagem ei = new ExibirImagem(this,true,imagem);
        ei.setVisible(true);
    }//GEN-LAST:event_jButton_PaddingtonActionPerformed

    private void jButton_HorribleBossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HorribleBossActionPerformed
        String imagem = "./5.jpg";
        
        ExibirImagem ei = new ExibirImagem(this,true,imagem);
        ei.setVisible(true);
    }//GEN-LAST:event_jButton_HorribleBossActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarregaImagemV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarregaImagemV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarregaImagemV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarregaImagemV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarregaImagemV2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DebyELoide;
    private javax.swing.JButton jButton_Guardioes;
    private javax.swing.JButton jButton_Hobbit;
    private javax.swing.JButton jButton_HorribleBoss;
    private javax.swing.JButton jButton_Paddington;
    private javax.swing.JButton jButton_Sair;
    // End of variables declaration//GEN-END:variables
}
